name: Deploy Reveal.js Slides

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install reveal-md
        run: npm install -g reveal-md

      - name: Build slides
        run: |
            mkdir -p ./static

            touch index.md
            echo "---" > index.md
            echo "title: 欢迎来到 SI 100+" >> index.md
            echo "theme: simple" >> index.md
            echo "highlightTheme: github" >> index.md
            echo "css: assets/custom.css" >> index.md
            echo "---" >> index.md
            echo "## SI 100+: 信息科学入门指南 Slides 页" >> index.md
            echo >> index.md

            echo "<div style=\"column-count:2; column-gap:0px; padding: 1vh\">" >> index.md
            echo >> index.md

            count=0
            find . -name '*.md' \
              ! -name 'README.md' \
              ! -name 'ISSUES.md' \
              ! -name 'index.md' \
              ! -exec grep -q 'marp: true' {} \; \
              -print | sort | while read -r file; do

              output_dir="static/$(basename ${file%.md})"
              echo "Processing $output_dir"

              if [ $count -eq 12 ]; then
                echo "</hr>" >> index.md
              fi

              echo "- [$(basename ${file%.md})](./$(basename ${file%.md}))" >> index.md

              reveal-md $file --static $output_dir --template ./assets/reveal.html --preprocessor ./assets/preproc.js --scripts assets/menu/menu.js,assets/inject.js
              file_dir=$(dirname $file)
              if [ -d "$file_dir/images" ]; then
                cp -r $file_dir/images $output_dir
              fi

              count=$((count + 1))
            done

            echo "</div>" >> index.md
            echo >> index.md

            echo >> index.md
            echo "---" >> index.md
            echo "## SI 100+ Notebook 页" >> index.md

            find . -name "*.ipynb" | sort | while read -r file; do

                echo "Processing $file"
                pure_path="${file//.\//\/}"
                echo "- [$(basename ${file%.md})](https://nbviewer.org/github/teafrogsf/SI100Plus/blob/main$pure_path)" >> index.md

            done

            reveal-md index.md --static static
            rm index.md

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static
